# -*- coding: utf-8 -*-
"""sefelin 074.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TwBtiVa-kFg0Sbzqm6mNrZz44Tlu72iR
"""

# konversi suhu dari Celcius ke Fahrenheit, Kelvin, dan Reamur.
def suhu(y): 
  far = (y *9/5)+32
  kel = 273 + y
  rea = 4/5 * y
  print("suhu dalam Fahrenheit: ", far , "F")
  print("suhu dalam kelvin: ", kel , "K")
  print("suhu dalam reamur: ", rea , "R")
b = int (input("masukan nilai suhu dalam celcius untuk di konversikan : "))
suhu(b)

# inpuran data dengan tema benda (motor)
motor = input("masukan merk motor yang kamu ginakan : ")
plat_motor = int (input("masukan plat motor yang kamu ginakan : "))
harga_motor = input("masukan harga motor yang kamu ginakan : ")
warna_motor = input("masukan warna motor yang kamu ginakan : ")
pajak_motor = input("masukan berapa pajak motor yang akan kamu bayar : ")
list = []
list.append(motor)
list.append(plat_motor)
list.append(harga_motor)
list.append(warna_motor)
list.append(pajak_motor)
print(list[0])
print(list[1])
print(list[2])
print(list[3])
print(list[4])
print("variabel motor       :", motor,       "bertipe data :", type (motor),        end="\n\n")
print("variabel plat_motor  :", plat_motor,  "bertipe data :", type (plat_motor),   end="\n\n")
print("variabel harga_motor :", harga_motor, "bertipe data :", type (harga_motor),  end="\n\n")
print("variabel warna_motor :", warna_motor, "bertipe data :", type (warna_motor),  end="\n\n")
print("variabel pajak_motor :", pajak_motor, "bertipe data :", type (pajak_motor),  end="\n\n")